---

- hosts: all
  become: true
  tasks:

  - name: update repo index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: install apache2 package
    tags: apache
    apt:
      name: apache2
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: add php support for apache
    tags: debian,php
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Debian" and ansible_distribution_version == "12"
